name: Deploy to staging environment for PR

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  delete_stack:
    if: |-
      (github.event.pull_request.action != 'opened' ||
      github.event.pull_request.action != 'reopened')
      && contains(github.event.pull_request.labels.*.name, 'with_delete')
    uses: ./.github/workflows/delete_stack_template.yaml
    with:
      stack-name: debug-env-${{ github.event.pull_request.number }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_GITHUB_OIDC_ROLE_NAME: ${{ secrets.AWS_GITHUB_OIDC_ROLE_NAME }}
  deploy:
    if: ${{ always() }}
    needs: [delete_stack]
    uses: ./.github/workflows/deploy_job_template.yaml
    with:
      pr-number: ${{ github.event.pull_request.number }}
      stack-name: eecs-debug-${{ github.event.pull_request.number }}
      s3-dir: PR-${{ github.event.pull_request.number }}
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_GITHUB_OIDC_ROLE_NAME: ${{ secrets.AWS_GITHUB_OIDC_ROLE_NAME }}
      SLACK_APP_CLIENT_ID: ${{ secrets.SLACK_APP_CLIENT_ID }}
      SLACK_APP_CLIENT_SECRET: ${{ secrets.SLACK_APP_CLIENT_SECRET }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      CLIENT_URL: ${{ secrets.CLIENT_URL }}
      CLIENT_URL_OWN_DOMAIN: "https://example.com"
